// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCXcPXrYSn2MPX7l9QdJEgkRmmil9z9s',
    appId: '1:766573291475:web:2610206d8d4e39bf523126',
    messagingSenderId: '766573291475',
    projectId: 'vr-portfolio-root',
    authDomain: 'vr-portfolio-root.firebaseapp.com',
    storageBucket: 'vr-portfolio-root.appspot.com',
    measurementId: 'G-LMT7Y2CSDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGjS4J_6SKGupH6mTUg7dsmA3ldSyHWw',
    appId: '1:766573291475:android:2656238567d6afea523126',
    messagingSenderId: '766573291475',
    projectId: 'vr-portfolio-root',
    storageBucket: 'vr-portfolio-root.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdtSM8QA-1FVELkbl76BsnV0kv8z_eUiU',
    appId: '1:766573291475:ios:52845207a4a46490523126',
    messagingSenderId: '766573291475',
    projectId: 'vr-portfolio-root',
    storageBucket: 'vr-portfolio-root.appspot.com',
    iosBundleId: 'com.voidroot.portfolio.vrportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdtSM8QA-1FVELkbl76BsnV0kv8z_eUiU',
    appId: '1:766573291475:ios:52845207a4a46490523126',
    messagingSenderId: '766573291475',
    projectId: 'vr-portfolio-root',
    storageBucket: 'vr-portfolio-root.appspot.com',
    iosBundleId: 'com.voidroot.portfolio.vrportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPCXcPXrYSn2MPX7l9QdJEgkRmmil9z9s',
    appId: '1:766573291475:web:4c8af0faa8b329f8523126',
    messagingSenderId: '766573291475',
    projectId: 'vr-portfolio-root',
    authDomain: 'vr-portfolio-root.firebaseapp.com',
    storageBucket: 'vr-portfolio-root.appspot.com',
    measurementId: 'G-ED43GSN0L7',
  );
}
